#!/usr/bin/python
import sys
import os
import getpass

logfilename = "/tmp/swarmplay-"+getpass.getuser()+".log"
f = open(logfilename,"w")
sys.stderr = f

tribler_root = os.path.abspath(os.path.dirname(__file__))
os.chdir(tribler_root)

sys.path.insert(0, tribler_root)
import BaseLib.Plugin.BackgroundProcess
import BaseLib.Transport.SwarmEngine

BaseLib.Plugin.BackgroundProcess.DEBUG = False
if len(sys.argv) > 1 and sys.argv[1] == 'debug':
   BaseLib.Plugin.BackgroundProcess.DEBUG = True

BaseLib.Transport.SwarmEngine.start()
